In [1]:
import pandas as pd

In [5]:
path2020 ='dados/LeitoOcupacao_2020.csv'
path2021 ='dados/LeitoOcupacao_2021.csv'
path2022 ='dados/LeitoOcupacao_2022.csv'

In [6]:
df2020 = pd.read_csv(path2020)
df2021 = pd.read_csv(path2021)
df2022 = pd.read_csv(path2022)

/tmp/ipykernel_5305/4287290986.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df2020 = pd.read_csv(path2020,sep=',')

,Unnamed: 0,_id,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,...,origem,_p_usuario,estadoNotificacao,municipioNotificacao,estado,municipio,excluido,validado,_created_at,_updated_at
0,0,p5Ez41Zu6B,2020-04-14T03:00:00.000Z,2303167,0.0,0.0,0.0,0.0,NaN,NaN,...,aplicacao-web,_User$auVMjEVEVz,Santa Catarina,Itapema,Santa Catarina,Itapema,True,False,2020-04-15T13:44:30.085Z,2020-04-16T13:56:13.656Z
1,1,eUOMsSt7T7,2020-04-15T03:00:00.000Z,5935377\t,1.0,0.0,0.0,0.0,NaN,NaN,...,parse-cloud,_User$WBa5nfe9P9,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,Rio de Janeiro,False,False,2020-04-15T13:50:47.256Z,2020-08-01T20:08:13.116Z
2,2,QaG4oIBrMa,2020-04-15T14:57:16.255Z,0012599,15.0,1.0,3.0,2.0,NaN,NaN,...,parse-cloud,_User$6oxZQHBPQ7,Rio de Janeiro,Niterói,Rio de Janeiro,Niterói,False,False,2020-04-15T15:20:57.033Z,2020-08-01T20:02:12.729Z
3,3,ifya31F3ZF,2020-03-24T03:00:00.000Z,2562871,9.0,0.0,1.0,0.0,NaN,NaN,...,parse-cloud,_User$fhufIbmR9C,Ceará,Várzea Alegre,Ceará,Várzea Alegre,False,False,2020-04-15T16:58:32.839Z,2020-08-01T21:40:37.624Z
4,4,dkurDhelx9,2020-04-01T03:00:00.000Z,2252228,26.0,0.0,1.0,0.0,NaN,NaN,...,parse-cloud,_User$tkAdHTNhC9,Rio Grande do Sul,Encantado,Rio Grande do Sul,Encantado,False,False,2020-04-15T17:02:53.877Z,2020-08-01T21:37:53.664Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
554674,1515227,8GSrENxNvK,2020-06-29T03:00:00.000Z,2302543,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$6aMgFYR3IC,Santa Catarina,Salto Veloso,Santa Catarina,Salto Veloso,False,False,2022-07-04T21:01:08.432Z,2022-07-04T21:01:08.432Z
554675,1515232,zSNicxkRGg,2020-07-01T03:00:00.000Z,2302543,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$6aMgFYR3IC,Santa Catarina,Salto Veloso,Santa Catarina,Salto Veloso,False,False,2022-07-04T21:04:29.042Z,2022-07-04T21:04:29.042Z
554676,1528884,l67Tu9rHto,2020-07-23T03:00:00.000Z,3030415,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$NrusnwHfug,Rio de Janeiro,Petrópolis,Rio de Janeiro,Petrópolis,False,False,2022-07-25T13:42:18.642Z,2022-07-25T13:42:18.642Z
554677,1540898,AOpnJPbOk8,2020-08-15T03:00:00.000Z,2499363,NaN,NaN,NaN,NaN,0.0,1.0,...,parse-cloud,_User$cS8zk5UqNn,Ceará,Fortaleza,Ceará,Fortaleza,False,False,2022-08-18T14:37:49.510Z,2022-08-18T14:37:49.510Z
554678,1545472,EmeNu3zpnq,2020-08-27T03:00:00.000Z,2373513,NaN,NaN,NaN,NaN,0.0,0.0,...,parse-cloud,_User$XjBJBtqkHG,Ceará,Acarape,Ceará,Acarape,False,False,2022-08-29T11:08:50.059Z,2022-08-29T11:08:50.059Z

In [12]:
df_all = pd.concat([df2020,df2021,df2022])

In [13]:
df_all.drop(
    [
      'Unnamed: 0',
      '_id',
      '_p_usuario',
      'municipioNotificacao',
      'estadoNotificacao',
      'origem',
      'excluido',
      'validado',
      '_created_at',
      '_updated_at',
     'estado',
     'municipio'

    ], 
    axis=1, inplace=True
)
df_all

,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas
0,2020-04-14T03:00:00.000Z,2303167,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
1,2020-04-15T03:00:00.000Z,5935377\t,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0
2,2020-04-15T14:57:16.255Z,0012599,15.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
3,2020-03-24T03:00:00.000Z,2562871,9.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
4,2020-04-01T03:00:00.000Z,2252228,26.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267247,2022-10-20T03:00:35.024Z,5586348,NaN,NaN,NaN,NaN,0.0,0.0,4.0,41.0,0.0,0.0,0.0,0.0
267248,2022-10-20T03:00:21.805Z,2363070,NaN,NaN,NaN,NaN,0.0,0.0,17.0,50.0,0.0,0.0,0.0,0.0
267249,2022-10-20T03:00:00.000Z,2302748,NaN,NaN,NaN,NaN,0.0,0.0,0.0,34.0,1.0,0.0,0.0,0.0
267250,2022-10-20T03:00:09.641Z,2420015,NaN,NaN,NaN,NaN,0.0,0.0,9.0,35.0,0.0,0.0,0.0,0.0
267251,2022-10-20T02:00:17.207Z,5585422,NaN,NaN,NaN,NaN,4.0,0.0,43.0,22.0,0.0,0.0,0.0,1.0

In [42]:
df_all['anoNotificacao'] = pd.DatetimeIndex(df_all['dataNotificacao']).year
df_all['mesNotificacao'] = pd.DatetimeIndex(df_all['dataNotificacao']).month
df_all['dayNotificacao'] = pd.DatetimeIndex(df_all['dataNotificacao']).day

In [43]:
df_all

,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,anoNotificacao,mesNotificacao,dayNotificacao
0,2020-04-14T03:00:00.000Z,2303167,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2020,4,14
1,2020-04-15T03:00:00.000Z,5935377\t,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,2020,4,15
2,2020-04-15T14:57:16.255Z,0012599,15.0,1.0,3.0,2.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2020,4,15
3,2020-03-24T03:00:00.000Z,2562871,9.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2020,3,24
4,2020-04-01T03:00:00.000Z,2252228,26.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2020,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267247,2022-10-20T03:00:35.024Z,5586348,NaN,NaN,NaN,NaN,0.0,0.0,4.0,41.0,0.0,0.0,0.0,0.0,2022,10,20
267248,2022-10-20T03:00:21.805Z,2363070,NaN,NaN,NaN,NaN,0.0,0.0,17.0,50.0,0.0,0.0,0.0,0.0,2022,10,20
267249,2022-10-20T03:00:00.000Z,2302748,NaN,NaN,NaN,NaN,0.0,0.0,0.0,34.0,1.0,0.0,0.0,0.0,2022,10,20
267250,2022-10-20T03:00:09.641Z,2420015,NaN,NaN,NaN,NaN,0.0,0.0,9.0,35.0,0.0,0.0,0.0,0.0,2022,10,20
267251,2022-10-20T02:00:17.207Z,5585422,NaN,NaN,NaN,NaN,4.0,0.0,43.0,22.0,0.0,0.0,0.0,1.0,2022,10,20

In [44]:
df_all['anoNotificacao'] = df_all['anoNotificacao'].astype('str')
df_all['mesNotificacao'] = df_all['mesNotificacao'].astype('str')
df_all['dayNotificacao'] = df_all['dayNotificacao'].astype('str')
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1566945 entries, 0 to 267251
Data columns (total 17 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   dataNotificacao        1566945 non-null  object
 1   cnes                   1566895 non-null  object
 2   ocupacaoSuspeitoCli    1014964 non-null  float64
 3   ocupacaoSuspeitoUti    1014964 non-null  float64
 4   ocupacaoConfirmadoCli  1014965 non-null  float64
 5   ocupacaoConfirmadoUti  1014965 non-null  float64
 6   ocupacaoCovidUti       558812 non-null   float64
 7   ocupacaoCovidCli       558812 non-null   float64
 8   ocupacaoHospitalarUti  558812 non-null   float64
 9   ocupacaoHospitalarCli  558812 non-null   float64
 10  saidaSuspeitaObitos    1566829 non-null  float64
 11  saidaSuspeitaAltas     1566841 non-null  float64
 12  saidaConfirmadaObitos  1566933 non-null  float64
 13  saidaConfirmadaAltas   1566932 non-null  float64
 14  anoNotificacao         1566945 non-null  object
 15  mesNotificacao         1566945 non-null  object
 16  dayNotificacao         1566945 non-null  object
dtypes: float64(12), object(5)
memory usage: 215.2+ MB

In [45]:
df_all = df_all.sort_values(by=['anoNotificacao','mesNotificacao','dayNotificacao'])

In [46]:
df_all.fillna("0", inplace=True)
df_all

,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,anoNotificacao,mesNotificacao,dayNotificacao
545631,2020-01-01T03:00:00.000Z,2733560,3.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,2020,1,1
545671,2020-01-01T03:00:00.000Z,2102595,5.0,0.0,6.0,0.0,0,0,0,0,0.0,0.0,0.0,1.0,2020,1,1
545780,2020-01-01T03:00:00.000Z,2172844,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,2020,1,1
545795,2020-01-01T03:00:00.000Z,2372270,5.0,0.0,2.0,0.0,0,0,0,0,1.0,0.0,0.0,0.0,2020,1,1
545931,2020-01-01T02:00:00.000Z,2572192,2.0,0.0,2.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,2020,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262055,2022-09-09T03:00:00.000Z,2218798,0,0,0,0,0.0,0.0,9.0,92.0,0.0,0.0,0.0,0.0,2022,9,9
262159,2022-09-09T03:00:00.000Z,2796376,0,0,0,0,0.0,1.0,0.0,14.0,0.0,0.0,0.0,1.0,2022,9,9
262460,2022-09-09T03:00:00.000Z,0209082,0,0,0,0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,2022,9,9
262741,2022-09-09T03:00:00.000Z,2639173,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2022,9,9
263517,2022-09-09T03:00:00.000Z,2525569,0,0,0,0,0.0,0.0,29.0,69.0,0.0,0.0,0.0,0.0,2022,9,9

In [47]:
df_all['anoNotificacao'] = df_all['anoNotificacao'].apply((lambda x: x.rjust(2, "0")))
df_all['mesNotificacao'] = df_all['mesNotificacao'].apply((lambda x: x.rjust(2, "0"))) 
df_all['dayNotificacao'] = df_all['dayNotificacao'].apply((lambda x: x.rjust(2, "0")))
df_all

,dataNotificacao,cnes,ocupacaoSuspeitoCli,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,anoNotificacao,mesNotificacao,dayNotificacao
545631,2020-01-01T03:00:00.000Z,2733560,3.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,2020,01,01
545671,2020-01-01T03:00:00.000Z,2102595,5.0,0.0,6.0,0.0,0,0,0,0,0.0,0.0,0.0,1.0,2020,01,01
545780,2020-01-01T03:00:00.000Z,2172844,0.0,0.0,0.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,2020,01,01
545795,2020-01-01T03:00:00.000Z,2372270,5.0,0.0,2.0,0.0,0,0,0,0,1.0,0.0,0.0,0.0,2020,01,01
545931,2020-01-01T02:00:00.000Z,2572192,2.0,0.0,2.0,0.0,0,0,0,0,0.0,0.0,0.0,0.0,2020,01,01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262055,2022-09-09T03:00:00.000Z,2218798,0,0,0,0,0.0,0.0,9.0,92.0,0.0,0.0,0.0,0.0,2022,09,09
262159,2022-09-09T03:00:00.000Z,2796376,0,0,0,0,0.0,1.0,0.0,14.0,0.0,0.0,0.0,1.0,2022,09,09
262460,2022-09-09T03:00:00.000Z,0209082,0,0,0,0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,2022,09,09
262741,2022-09-09T03:00:00.000Z,2639173,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2022,09,09
263517,2022-09-09T03:00:00.000Z,2525569,0,0,0,0,0.0,0.0,29.0,69.0,0.0,0.0,0.0,0.0,2022,09,09

In [49]:
df_all['datacode'] = df_all['anoNotificacao'] +  df_all['mesNotificacao'] + df_all['dayNotificacao']

In [51]:
df_all['saidaConfirmadaAltas'] = df_all['saidaConfirmadaAltas'].astype('int')
df_all['ocupacaoSuspeitoUti'] = df_all['ocupacaoSuspeitoUti'].astype('int')
df_all['ocupacaoConfirmadoCli'] = df_all['ocupacaoConfirmadoCli'].astype('int')
df_all['ocupacaoConfirmadoUti'] = df_all['ocupacaoConfirmadoUti'].astype('int')
df_all['ocupacaoCovidUti'] = df_all['ocupacaoCovidUti'].astype('int')
df_all['ocupacaoCovidCli'] = df_all['ocupacaoCovidCli'].astype('int')
df_all['ocupacaoHospitalarUti'] = df_all['ocupacaoHospitalarUti'].astype('int')
df_all['ocupacaoHospitalarCli'] = df_all['ocupacaoHospitalarCli'].astype('int')
df_all['saidaSuspeitaObitos'] = df_all['saidaSuspeitaObitos'].astype('int')
df_all['saidaSuspeitaAltas'] = df_all['saidaSuspeitaAltas'].astype('int')
df_all['saidaConfirmadaObitos'] = df_all['saidaConfirmadaObitos'].astype('int')
df_all['ocupacaoSuspeitoCli '] = df_all['ocupacaoSuspeitoCli'].astype('int')

In [53]:
df_all = df_all.groupby(['datacode']).sum()
df_all

/tmp/ipykernel_5305/750292640.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_all = df_all.groupby(['datacode']).sum()

,ocupacaoSuspeitoUti,ocupacaoConfirmadoCli,ocupacaoConfirmadoUti,ocupacaoCovidUti,ocupacaoCovidCli,ocupacaoHospitalarUti,ocupacaoHospitalarCli,saidaSuspeitaObitos,saidaSuspeitaAltas,saidaConfirmadaObitos,saidaConfirmadaAltas,ocupacaoSuspeitoCli
datacode,,,,,,,,,,,,
20200101,47,49,30,0,0,0,0,1,0,0,3,269
20200102,260,213,215,0,6,53,477,1,6,11,8,879
20200103,249,201,204,0,1,0,52,4,8,4,7,540
20200104,150,78,69,0,0,0,1,1,6,22,4,292
20200105,57,79,88,0,0,0,0,0,4,2,10,335
...,...,...,...,...,...,...,...,...,...,...,...,...
20221016,0,0,0,285,314,2988,14419,66,181,89,408,0
20221017,0,0,0,324,514,3647,17443,66,213,103,405,0
20221018,0,0,0,320,482,3668,17991,68,206,104,400,0
20221019,0,0,0,194,384,3041,15832,67,222,103,396,0
20221020,0,0,0,121,213,2532,13443,7,20,37,241,0

In [56]:
df_all.reset_index(inplace=True)

In [58]:
df_all.to_csv('brasil_ocupacao_daily.csv')